version: '3.9'

services:

  backend:
    build: .
    container_name: rag_backend

    command: uvicorn main:app --host 0.0.0.0 --port 8000

    ports:
      - "8000:8000"

    volumes:
      - ./vectorstore:/app/vectorstore
      - ./uploads:/app/uploads

  frontend:
    build: .
    container_name: rag_frontend

    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0

    ports:
      - "8501:8501"

    depends_on:
      - backend